### ISSUE TITLE
Firepicker Doesn't Work in Detached Mode on Mac OS X

### ISSUE THREAD

**Issue by trymbill** [thedarkone/firepicker#14]
I'm running Firebug 1.8.3 in detached mode (full screen) on Firefox 7.0.1 with Firepicker 1.3.6 on Mac OS X and when I click a color, the color value and color pops-out but the color selecting window pops out behind Firebug and isn't click-able. Clicking on it doesn't change anything.

Let me know if you need any more information.

Thanks,
Maggi

**Comment by thedarkone** [comment]
Hey,

this should be fixed in the newest version.

Thanks!

**Comment by verbatim** [comment]
I am still having this issue: 
http://www.flickr.com/photos/31792685@N02/6609717765/

Firefox 8.01
Firebug 1.84
Firepicker 1.37
Macintosh
Firebug window separated
